// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnY91fbD4qbi4AhkvdvHsZ7dB4Fwkoru0',
    appId: '1:229214527141:web:394a425ec54e9713b0374c',
    messagingSenderId: '229214527141',
    projectId: 'travel-guide-with-firebase',
    authDomain: 'travel-guide-with-firebase.firebaseapp.com',
    storageBucket: 'travel-guide-with-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGapRP6LdqSXvMCNliGhmNlHkynKgyAwg',
    appId: '1:229214527141:android:bce83a003a870e23b0374c',
    messagingSenderId: '229214527141',
    projectId: 'travel-guide-with-firebase',
    storageBucket: 'travel-guide-with-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4kZOgx_VPVFLW3uzBWeMRmJS8-vWYRa4',
    appId: '1:229214527141:ios:1ff224d5240400e0b0374c',
    messagingSenderId: '229214527141',
    projectId: 'travel-guide-with-firebase',
    storageBucket: 'travel-guide-with-firebase.appspot.com',
    iosBundleId: 'com.example.travelGuideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4kZOgx_VPVFLW3uzBWeMRmJS8-vWYRa4',
    appId: '1:229214527141:ios:96cd96761534c831b0374c',
    messagingSenderId: '229214527141',
    projectId: 'travel-guide-with-firebase',
    storageBucket: 'travel-guide-with-firebase.appspot.com',
    iosBundleId: 'com.example.travelGuideApp.RunnerTests',
  );
}
